### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Igorbunow** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#11]
Environment:
  Redmine version                4.1.1.devel
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

```
# rake redmine:plugins:migrate RAILS_ENV=production

ProjectsHelper MISS   instance_methods  project_settings_tabs  < (SM::HO::ProjectsOverride::ProjectEnumerations)
/home/www/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/lib/helpers/smile_helpers_projects.rb:144:in `prepended'
/home/www/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:74:in `prepend'
/home/www/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:74:in `prepend_in'
/home/www/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:164:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:605:in `catch'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `each'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:89:in `prepare!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/home/www/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by Utopism** [comment]
Hi,
seems there is a conflict with another plugin.
Can you give the list of the Redmine plugins you have installed on your server ?

**Comment by Igorbunow** [comment]
Hi, may be the meter in other plugin

Redmine plugins:
  clipboard_image_paste          1.13
  export_docx                    1.3.1
  redmine_ckeditor               1.2.3
  redmine_code_review            1.0.0
  redmine_codemirror             0.0.1
  redmine_cut_tag                2.0.8
  redmine_git_remote             0.0.1
  redmine_issue_dynamic_edit     0.4.9
  redmine_issue_templates        1.0.1
  redmine_mail_from              1.3.0
  redmine_mail_reminder          3.0.0.0001
  redmine_rouge                  0.0.1
  redmine_smile_project_enumerations_custom_field_format 1.3.13
  redmine_wiki_extensions        0.9.0
  sidebar_hide                   0.0.8

and other tools are:

SCM:
  Subversion                     1.10.4
  Git                            2.20.1
  Filesystem                     
  GitRemote                      2.20.1

**Comment by Igorbunow** [comment]
And it generate error 500, when i try to open wiki or project settings:

```
Started GET "/projects/wiki/settings" for 91.188.173.18 at 2020-04-18 18:36:42 +0300
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"wiki"}
  Current user: admin (id=1)
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/settings.html.erb within layouts/base (174.2ms)
Completed 500 Internal Server Error in 310ms (ActiveRecord: 77.3ms)
  
ActionView::Template::Error (super: no superclass method `project_settings_tabs' for #<#<Class:0x0000564ee54797a0>:0x0000564ee2100068>
Did you mean?  project_issues_path):
    1: <h2><%=l(:label_settings)%></h2>
    2: 
    3: <%= render_tabs project_settings_tabs %>
    4: 
    5: <% html_title(l(:label_settings)) -%>
  
plugins/redmine_wiki_extensions/lib/wiki_extensions_projects_helper_patch.rb:22:in `project_settings_tabs'
plugins/redmine_smile_project_enumerations_custom_field_format/lib/helpers/smile_helpers_projects.rb:22:in `project_settings_tabs_with_project_enumerations'
plugins/redmine_code_review/lib/code_review_projects_helper_patch.rb:22:in `project_settings_tabs'
plugins/redmine_wiki_extensions/lib/wiki_extensions_projects_helper_patch.rb:22:in `project_settings_tabs'
app/views/projects/settings.html.erb:3:in `_app_views_projects_settings_html_erb___1473026416918998905_47448427059100'
lib/redmine/sudo_mode.rb:64:in `sudo_mode'

```

after disable plugin everything is ok

**Comment by Utopism** [comment]
Hi,

I think **redmine_issue_templates** is the one that conflicts. I'm making some tests and I will tell you I this can be fixed.

**Comment by Utopism** [comment]
Hi @Igorbunow 

* Just tested with **redmine_issue_templates** with no issue.
* I'm checking **redmine_wiki_extensions** now.

**Comment by Utopism** [comment]
Hi,

The issue was exactly an uncompatibility with the **redmine_wiki_extensions** plugin.
* You can install new version of my plugin **V1.3.14**
* You will have to replace the source code of **plugins/redmine_wiki_extensions/lib/wiki_extensions_projects_helper_patch.rb** by :
```
# Wiki Extensions plugin for Redmine
# Copyright (C) 2009-2017  Haruyuki Iida
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require_dependency 'projects_helper'

module ProjectsHelperMethodsWikiExtensions
  def self.prepended(base)
    base.module_eval do
      def project_settings_tabs_with_wiki_extensions
        tabs = project_settings_tabs_without_wiki_extensions
        action = {:name => 'wiki_extensions',
          :controller => 'wiki_extensions_settings',
          :action => :show,
          :partial => 'wiki_extensions_settings/show',
          :label => :wiki_extensions}

        tabs << action if User.current.allowed_to?(action, @project)

        tabs
      end
   end

    base.instance_eval do
      alias_method :project_settings_tabs_without_wiki_extensions, :project_settings_tabs
      alias_method :project_settings_tabs, :project_settings_tabs_with_wiki_extensions
    end
  end
end

ProjectsHelper.prepend(ProjectsHelperMethodsWikiExtensions)
```
* I am adding a pull request for this for the plugin maintainer

**Comment by Utopism** [comment]
See, https://github.com/haru/redmine_wiki_extensions/issues/16 for the pull request.

**Comment by Igorbunow** [comment]
Thanks a lot! After you patch in redmine_wiki_extensions, it installs perfectly well, but running only with: 
bundle exec rails server webrick -e production -b ip -p 80

But i have a problem on unicorn:

/usr/bin/ruby2.5 /usr/local/bin/bundle exec unicorn_rails -E production -c /home/www/redmine/config/unicorn.rb -D
`master failed to start, check stderr log for details`

my config.ru:

```
require 'unicorn/worker_killer'
 max_request_min =  500
 max_request_max =  600
 # Max requests per worker
 use Unicorn::WorkerKiller::MaxRequests, max_request_min, max_request_max
 oom_min = (240) * (1024**2)
 oom_max = (260) * (1024**2)
 # Max memory size (RSS) per worker
 use Unicorn::WorkerKiller::Oom, oom_min, oom_max

require ::File.expand_path('../config/environment',  __FILE__)
run RedmineApp::Application
```
config/unicorn.rb:

 ```
   worker_processes 1   #Количество процессов master + 1 потомок
      working_directory "/home/www/redmine/" #Домашний каталог redmine
      preload_app true
      timeout 100
      listen "/home/www/redmine/tmp/sockets/unicorn.sock", :backlog => 64 #путь до unix сокета к нему будет обращаться nginx
      pid "/home/www/redmine/tmp/pids/unicorn.pid"
      stderr_path "/home/www/redmine/log/unicorn.stderr.log"
      stdout_path "/home/www/redmine/log/unicorn.stdout.log"
      before_fork do |server, worker|
          defined?(ActiveRecord::Base) and
              ActiveRecord::Base.connection.disconnect!
      end
      after_fork do |server, worker|
          defined?(ActiveRecord::Base) and
              ActiveRecord::Base.establish_connection
      end
```

error log unicorn.stderr.log:

```
I, [2020-04-25T09:02:30.747388 #4829]  INFO -- : Refreshing Gem list
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/strscan.so: warning: already initialized constant StringScanner::Version
/usr/lib/x86_64-linux-gnu/ruby/2.5.0/strscan.so: warning: already initialized constant StringScanner::Id
/home/www/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:80:in `<top (required)>': undefined method `to_prepare' for nil:NilClass (NoMethodError)
Did you mean?  to_param
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
  from /home/www/redmine/lib/redmine/plugin.rb:181:in `block in load'
  from /home/www/redmine/lib/redmine/plugin.rb:172:in `each'
  from /home/www/redmine/lib/redmine/plugin.rb:172:in `load'
  from /home/www/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
  from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
  from /usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
  from /usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
  from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
  from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
  from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
  from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
  from /home/www/redmine/config/environment.rb:16:in `<top (required)>'
  from config.ru:15:in `require'
  from config.ru:15:in `block in <main>'
  from /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `instance_eval'
  from /var/lib/gems/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `initialize'
  from config.ru:1:in `new'
  from config.ru:1:in `<main>'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `eval'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `block in builder'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/bin/unicorn_rails:139:in `block in rails_builder'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:794:in `build_app!'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:141:in `start'
  from /var/lib/gems/2.5.0/gems/unicorn-5.5.4/bin/unicorn_rails:209:in `<top (required)>'
  from /usr/local/bin/unicorn_rails:23:in `load'
  from /usr/local/bin/unicorn_rails:23:in `<main>'
```

**Comment by Utopism** [comment]
Hi @Igorbunow 
to_prepare is called from Rails.configuration, that is a core Rails object, and that should be initialized.
So there is a problem with your unicorn configuration I suppose.

**Comment by Utopism** [comment]
This is un-related to the issue, so I'll close this one.

**Comment by Utopism** [comment]
Perhaps you have to enable **preload_app** in unicorn configuration :
See :
* https://stackoverflow.com/questions/18895433/referring-to-rails-from-the-unicorn-config-file
* https://yhbt.net/unicorn/Unicorn/Configurator.html#method-i-preload_app
