### ISSUE TITLE
undefined method `to_prepare' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bon9it** [Smile-SA/redmine_smile_project_enumerations_custom_field_format#13]
Redmine: 4.1.0.Stable
```
/home/redmine/redmine/plugins/redmine_smile_project_enumerations_custom_field_format/init.rb:80:in `<top (required)>': undefined method `to_prepare' for nil:NilClass (NoMethodError)
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
        from /home/redmine/redmine/lib/redmine/plugin.rb:181:in `block in load'
        from /home/redmine/redmine/lib/redmine/plugin.rb:172:in `each'
        from /home/redmine/redmine/lib/redmine/plugin.rb:172:in `load'
        from /home/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/lib/ruby/2.4.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
        from /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
        from config.ru:4:in `require'
        from config.ru:4:in `block in <main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `instance_eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/rack-2.0.8/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.2/lib/unicorn.rb:54:in `eval'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.2/lib/unicorn.rb:54:in `block in builder'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.5.2/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.2/lib/unicorn/http_server.rb:794:in `build_app!'
        from /home/redmine/data/tmp/bundle/ruby/2.4.0/gems/unicorn-5.5.2/lib/unicorn/http_server.rb:141:in `start'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/gems/unicorn-5.5.2/bin/unicorn_rails:209:in `<top (required)>'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `load'
        from /home/redmine/redmine/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `<main>'
```
Seems it is able to be fixed using https://github.com/ruby-grape/grape/issues/1666

**Comment by Utopism** [comment]
Hi, just made a small change that could fix your issue (V1.3.15)

**Comment by Utopism** [comment]
@bon9it can you check ?

**Comment by Utopism** [comment]
@bon9it closing the issue, I can re-open it, if you give some related news.
